version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=iit
      - POSTGRES_PASSWORD=anhemiit123
      - POSTGRES_DB=iit
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  pointdb:
    container_name: pointdb
    image: postgis/postgis
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=iit
      - POSTGRES_PASSWORD=anhemiit123
      - POSTGRES_DB=iit
    volumes:
      - ./pointdata:/var/lib/postgresql/data
