name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Cache
      uses: actions/cache@v3.3.2
      with:
        key: gha
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        tags: ${{secrets.DOCKER_USERNAME}}/map:latest
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        secrets: 
          DATABASE_URL=${{secrets.DATABASE_URL}}
          ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}
          REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}}
          
              
